# assets_list.py

# Список торговых пар (Binance Futures)
SYMBOLS = [
    'BTC/USDT:USDT', 'ETH/USDT:USDT', 'SOL/USDT:USDT', 'XRP/USDT:USDT', 'ADA/USDT:USDT', 
    'AVAX/USDT:USDT', 'DOGE/USDT:USDT', 'DOT/USDT:USDT', 'LINK/USDT:USDT', 'MATIC/USDT:USDT', 
    'TON/USDT:USDT', 'SHIB/USDT:USDT', 'LTC/USDT:USDT', 'TRX/USDT:USDT', 'BCH/USDT:USDT', 
    'NEAR/USDT:USDT', 'UNI/USDT:USDT', 'APT/USDT:USDT', 'ARB/USDT:USDT', 'OP/USDT:USDT', 
    'INJ/USDT:USDT', 'FIL/USDT:USDT', 'LDO/USDT:USDT', 'STX/USDT:USDT', 'SUI/USDT:USDT', 
    'SEI/USDT:USDT', 'RNDR/USDT:USDT', 'FET/USDT:USDT', 'TIA/USDT:USDT', 'GALA/USDT:USDT'
]

TIMEFRAME = '1h'
LIMIT = 1000  # Количество свечей
